---
users:
  - default:
    name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_import_id: None
    lock_passwd: false
    passwd: $6$rounds=4096$1.HZZNYE0oHMsX$u4abqZEhY/oMW7.OT2aWtXEy5JWrtahqlhBM6L7IXOgYXeUAfodfTb/wQPuDGwT4sX6bLZ4JbnILnazCO7cO11
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbF9qSH4y+xO2Su8QDtpvwHSmRihQAqHM/CYR+4UYJJ8iUNmfjaPaBXnw56WPGX0xU5Ql2fYg3/4UiL3OV/JTNqy9OC6Gu4Q2OtJq/kTvpS6q3Q5l4xbTFj+CTlb9E89IhT4XnATlxesD9mfcwxtk2H86z+ED6PI1Yx82zCLFhSXpe5w6OjxJuA+m49W1g8y4aDfHwNCJvZ6xb6jbNHfy3xToq581PIpYDqxdh0jkTiXZDiMqNPeFHqFiS5m3CTpFxtHukAqSexvS7lq1F8Vd9WMWTS90HlSem0cDgWdIdOmN4dZi90PiFJk1SLXhzZgHwmKtM3qlYGGxWbq1n223XjyMwmhsnq1uMt0AytxKYMtt7SRW/3Ua6P4nX6H7Q2eEVrkB788yc8fozZHKkR0VKgKfBVq9nptvGblcphS3p3QV/MuhVSb8dg+8p0vomiVcT1eYUFVCebpT9o6Fnzu3JE+q99TD2eiBaTGjLBc1k+fjGOoOAgEz1sihE9FvBj/Da+PB6kguLJG68DRW57WvcBBlReuhBOVwGPlH0SyRiDo6X4Wy1oQvvbPpGQmCBSsJet7+kFXWJ8sGf5nHitkxv2eOQgOZIigb45uGNtM8nScFyczhjW3YHGATgpsJbfJxusJxPu5CnuOgQuX9jZwH6lXGLYarylFd6sTGPoveqaQ== noelzilla@gmail.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGGhqQ1pxAeOffilgkz473sFhmldgxc39+cj8WKLC6m7ff3GOH/3RiUDkvkxA6aNic84syzb+bqeiCqdwnWAJ0wEbBtSvtph+wwxENQCwBzBNs9euKv8RqV6NyImDTMJNSaoLwvU4z4/vIlhhTTWFyZoCRBl/rXljUSu5qIXLF+4Ip/aH0wpyEimCa1X91XmJWDPSKyHQhK3sipOotN8MhqnvQrs4XsW5mE+169e9iPfC+OIyy8WUuGPhR55IOYdTjveMlkykwznHRdM6p9tKplr+HHDezXubW72zQl0zf/gfHEMIur0vXgStAf5R451nG5dsrOf1wPOREhIwPA051WVslg6zoLbGpWCsp81qKAD7a/NAU1YaAFp4LxvNbzwQCf7lXyiD88j4S5fIq2x3qZ53z7qwnxxR/ejWv6WvgT2chwBmNLUHgulVE5cWTiqEQBnEcxzgr4RLIgCHMnwSyZysdwJEQc9OEA+hL888sh6uo2EU/5czTfB8+IUzicgil8c7oFYeJvlBezweFl9Kw5rSeWn4v5AoDIHs9cM1MMoVx8uxz9wk/xp+RmnVZw7A0l1RKrmSxC7q3xOt5GupGkiZMu8ue5PNxOciP8TEnaxF75yp88EtOJApypn+pAoYjX0LeWhZY88PIqOhhE4rL6cVRdSx+yb6La2oh7PlmTQ== noel.murphy@smartbear.com
package_update: true
package_upgrade: true
packages:
  # list of useful packages to install
  - avahi-daemon
  - git
  - vim
  - curl
  - wget
